config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#index"
  get '/myconcerts', to: 'static_pages#index'

  resources :concerts, only: [:create, :index, :show] do
    resources :comments
    resources :myconcerts, only: [:index]
  end


  namespace :api do
    namespace :v1 do
      resources :concerts do
        resources :comments
      end

      resources :myconcerts, only: [:create, :index, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :concert
  belongs_to :user
  validates :text, presence: true, length: { maximum: 1000, message: 'must be less than 1000 characters' }
  validates :text, length: { minimum: 10, message: 'must be at least 10 characters' }
end

app/models/concert.rb
class Concert < ApplicationRecord
  has_many :comments
  has_many :myconcerts
  has_many :users, through: :myconcerts

  validates :artist, presence: true
  validates :venue, presence: true
  validates :start_date, presence: true
  validates :jambase_id, presence: true, numericality: true

end

app/models/jambase.rb
class Jambase
  include HTTParty

  TOKEN = "aggz2n9p2engnfa2fynn4gah"

  def self.base_url
    "http://api.jambase.com/events"
  end

  def self.get_events(zip_code)
    url = "#{base_url}?zipCode=#{zip_code}&api_key=#{TOKEN}"
    data = HTTParty.get(url, {format: :json})
    concerts = []
    data["Events"].each do |event|
      concert = Concert.find_or_create_by(
        jambase_id: event["Id"],
        artist: event["Artists"][0]["Name"],
        venue: event["Venue"]["Name"],
        start_date: event["Date"],
        ticket_url: event["TicketUrl"])

        concerts << concert
    end

    return concerts

  end
end

app/models/myconcert.rb
class Myconcert < ApplicationRecord
  belongs_to :user
  belongs_to :concert

  validates :artist, presence: true
  validates :venue, presence: true
  validates :start_date, presence: true
  validates :ticket_url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :myconcerts
  has_many :concerts, through: :myconcerts

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update]

  def index
    @concert = Concert.find(params[:concert_id])
    @comment = @concert.comments
    render json: @comments, adapter: :json
  end

  def update
    @concert = Concert.find(params[:concert_id])
    comment = Comment.find(params[:id])
    user_email = review.user

    # if review.save!
    #   ReviewMailer.review_email(user_email).deliver
    #
    #
    #   render json: {
    #     status: 201,
    #     message: "Comment saved!",
    #     review: review,
    #   }.to_json
    # else
    #   render json: {
    #     status: 500,
    #     review: review,
    #     up_style: up_style,
    #     down_style: down_style
    #   }.to_json
    # end
  end
end

app/controllers/api/v1/concerts_controller.rb
class Api::V1::ConcertsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def index
    render json: Concert.all, adapter: :json
  end

  def create
    data = JSON.parse(request.body.read)
    zip_code = data["zipCode"]
    concert_objects = Jambase.get_events(zip_code)
    render json: concert_objects, adapter: :json
  end

  def show
    concert = Concert.find(params[:id])
    comments = concert.comments.order(created_at: :desc)
    render json: { concert: concert, comments: comments }, adapter: :json
  end

  # private
  #   def concert_params
  #   params.require(:concert).permit(
  #     :zip_code
  #   )
  # end
end

app/controllers/api/v1/myconcerts_controller.rb
class Api::V1::MyconcertsController < ApplicationController
  skip_before_action :protect_from_forgery

  def index
    @myconcert = Myconcert.where(user_id: current_user.id)
    render json: @myconcert
  end

  def destroy
    Myconcert.destroy(params[:id])
    @myconcert = Myconcert.where(user_id: current_user.id)
    render json: @myconcert
  end

  def create
    data = JSON.parse(request.body.read)
    if Myconcert.exists?(user_id: current_user.id, body: data["body"])
      @myconcert = Myconcert.where(user_id: current_user.id, body: data["body"])
      render json: @myconcert
    else
      @myconcert = Myconcert.create(user_id: current_user.id, body: data["body"])
      render json: @myconcert
    end
  end
end

private
  def my_concerts_params
    params.require(:myconcert).permit(:user_id, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    render template: 'static_pages/index'
  end

  def new
    @comment = Comment.new
    @concert = Concert.find(params[:concert_id])
  end

  def create
    @concert = Concert.find(params[:concert_id])
    @comment = Comment.new(comment_params)
    @comment.concert = @concert
    @comment.user = current_user

    if @comment.save
      redirect_to @concert, notice: 'New comment was successfully created.'
    else
      render :new
    end
  end

  def edit
    @concert = Concert.find(params[:concert_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @concert = Concert.find(params[:concert_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "Comment successfully updated"
      redirect_to comment_path(@concert.id)
    else
      flash[:alert] = "Unable to update. There was an error"
      render :edit
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    @concert = comment.concert
    if Comment.destroy(comment.id)
      flash[:notice] = "Your comment has been deleted."
    else
      flash[:alert] = "Error deleting comment."
    end
    redirect_to concert_path(@concert.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :jambase_id)
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index;

  end

  def create

  end

  def show
    @concert = Concert.find(params[:id])
    @user = current_user
  end
end

app/controllers/myconcerts_controller.rb
class MyconcertsController < ApplicationController
  def index
    render template: 'static_pages/index'
  end

  def new
    @myconcert = Myconcert.new
    @concert = Concert.find(params[:concert_id])
  end

  def create
    @concert = Concert.find(params[:concert_id])
    @myconcert = Myconcert.new(concert_params)
    @myconcert.concert = @concert
    @myconcert.user = current_user

    if @comment.save
      redirect_to @concert, notice: 'Saved to My Concerts!'
    else
      render :new
    end
  end

  # def destroy
  #   myconcert = Myconcert.find(params[:id])
  #   @myconcert = myconcert.concert
  #   if Myconcert.destroy(concert.id)
  #     flash[:notice] = "Concert removed."
  #   else
  #     flash[:alert] = "Error removing concert."
  #   end
  #   redirect_to myconcert_path
  # end

  private

  def myconcert_params
    params.require(:myconcert).permit(:artist, :venue, :ticket_url, :start_date)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<h3>Edit Comment for <%= @concert.artist %> on <%= @concert.start_date%></h3>
<%= link_to "Back to Concert Page", concert_path(@concert) %>

<%= form_for [@concert, @comment], :url => edit_concert_comment_path(@concert, @comment) do |f| %>

  <%= f.label :text, "Comment Text" %>
  <%= f.text_field :text %>
  <br /><br />

  <%= f.submit "Update Comment" %>


  <% if current_user.id == @comment.user_id %>
    <%= button_to "Delete", [@concert, @comment], method: :delete,
    data: {confirm: "You Sure?"} %>
  <% end %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<div class='columns small-8 callout'>
<%= form_for([@concert, @comment], html: { class: 'form'}) do |f| %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="columns small-8">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="columns small-4">
    <%= f.submit %>
  </div>
<% end %>
</div>


<%= link_to 'Back', concert_path(@concert) %>

app/views/concerts/index.html.erb
<div id="app">
</div>

app/views/concerts/show.html.erb
<!-- <h1> <%= @concert.artist %>  </h1>

<h4> <%= @concert.venue %>  </h4>
<h4> <%= @concert.start_date %> </h4>


<h1>Comments</h1>
<ul>

</ul> -->

<div id="app">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html.bg lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Headbangr </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: 'all' %>
    <%= javascript_include_tag "vendor/modernizr" %>
  </head>

  <body>
    <div id="header" class="container-fluid">

      <div class="navbar-left">
        <h2>Headbangr</h2>
      </div>

      <div class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <a href="/myconcerts">My Concerts</a>   /
        Signed in as <%= current_user.first_name %> <%= current_user.last_name %>   /
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign In', new_user_session_path %>   /
          <%= link_to 'Sign Up', new_user_registration_path %>
        <% end %>
        <p class="notice"> <%= notice %><%= alert %></p>
      </div>

    </div>
    &nbsp;
    <div class="container">
      <%= yield %>
      <%= javascript_include_tag "application" %>

    </div>

  </body>
</html>

<!DOCTYPE html>

app/views/myconcerts/index.html.erb
<div id="app">

</div>